-- Table: public.Categories

-- DROP TABLE IF EXISTS public."Categories";

CREATE TABLE IF NOT EXISTS public."Categories"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Type" integer NOT NULL,
    "IsFixed" boolean NOT NULL DEFAULT false,
    CONSTRAINT "Categories_pkey" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Categories"
    OWNER to gastos_user;

    -- Table: public.HarvestDetails

-- DROP TABLE IF EXISTS public."HarvestDetails";

CREATE TABLE IF NOT EXISTS public."HarvestDetails"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TransactionId" uuid NOT NULL,
    "ProductType" character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Almendra'::character varying,
    "QuantityKg" numeric(12,2) NOT NULL,
    "PricePerKg" numeric(12,2) NOT NULL,
    CONSTRAINT "HarvestDetails_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "HarvestDetails_TransactionId_key" UNIQUE ("TransactionId"),
    CONSTRAINT "FK_HarvestDetails_Transactions_TransactionId" FOREIGN KEY ("TransactionId")
        REFERENCES public."Transactions" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."HarvestDetails"
    OWNER to gastos_user;

    -- Table: public.Transactions

-- DROP TABLE IF EXISTS public."Transactions";

CREATE TABLE IF NOT EXISTS public."Transactions"
(
    "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "CategoryId" integer NOT NULL,
    "Type" integer NOT NULL,
    "Amount" numeric(12,2) NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "Date" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Transactions_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Transactions_Categories_CategoryId" FOREIGN KEY ("CategoryId")
        REFERENCES public."Categories" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Transactions"
    OWNER to gastos_user;
-- Index: IX_Transactions_CategoryId

-- DROP INDEX IF EXISTS public."IX_Transactions_CategoryId";

CREATE INDEX IF NOT EXISTS "IX_Transactions_CategoryId"
    ON public."Transactions" USING btree
    ("CategoryId" ASC NULLS LAST)
    TABLESPACE pg_default;